#################################################
# 로컬 ##
spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pre032?serverTimezone=Asia/Seoul
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true;
#################################################
# 서버 ##
#spring:
#  profiles:
#    include: oauth
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://pre032-database.cssqpsefshei.ap-northeast-2.rds.amazonaws.com:3306/pre032?serverTimezone=Asia/Seoul
#    username: admin
#    password: pre032032
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true;


#################################################

#ec2 주소: http://ec2-43-201-80-20.ap-northeast-2.compute.amazonaws.com:8080


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 651205845903-ijvbcuiaa7sfn9q0tr7i78h4301ggomp.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:3000/login/oauth2/code/google
          scope:
            - email
            - profile

          github:
            client-id: bb0d7862c04e3967a361
            client-secret: ed674a520e58843f2ba5d878639163b09fb13434
            redirect-uri: http://localhost:3000/login/oauth2/code/github
            scope:
              - user

          naver:
            client-id: 6t4rOk6C5GLccx8Uk0vT
            client-secret: 5GsLNWNX8c
            scope:
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 return해줌.(value에는 getAttributes()한 값들이 들어가있음)

server:
  servlet:
    encoding:
      force-response: true
jwt:
  #  원래는 그냥 입력하면 안되는데 환경변수 설정 귀찮아서 그냥 입력함
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-expiration-minutes: 30